// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TestApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Course", b =>
                {
                    b.Property<int>("idCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCourse"));

                    b.Property<bool>("mark")
                        .HasColumnType("bit");

                    b.Property<string>("nameCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCourse");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("idStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idStudent"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idStudent");

                    b.ToTable("students");
                });

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.Property<int>("sc_idC")
                        .HasColumnType("int");

                    b.Property<int>("sc_idS")
                        .HasColumnType("int");

                    b.HasKey("sc_idC", "sc_idS");

                    b.HasIndex("sc_idS");

                    b.ToTable("studentsCourses");
                });

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.HasOne("Course", "crs")
                        .WithMany("sc_C")
                        .HasForeignKey("sc_idC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student", "stdnts")
                        .WithMany("sc_S")
                        .HasForeignKey("sc_idS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("crs");

                    b.Navigation("stdnts");
                });

            modelBuilder.Entity("Course", b =>
                {
                    b.Navigation("sc_C");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Navigation("sc_S");
                });
#pragma warning restore 612, 618
        }
    }
}
